apiVersion: v1
kind: Service
metadata:
  labels:
    app: local-webserver
  name: local-webserver
  namespace: inverter-edge
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: local-webserver
  sessionAffinity: None