apiVersion: v1alpha1
kind: Fleet
metadata:
  name: basic-nginx-fleet
spec:
  selector:
    matchLabels:
      fleet: basic-nginx-fleet
  template:
    spec:
      os:
        image: quay.io/flightctl/flightctl-agent-basic-nginx:latest
