apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-server
  name: model-server
  namespace: inverter-edge
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: model-server
  sessionAffinity: None