---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ai-model-server-deployment.yaml
  - ai-model-service-service.yaml
  - local-webserver-deployment.yaml
  - local-webserver-service.yaml
  - local-webserver-mdns-route.yaml
  - control-loop-deployment.yaml