apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: local-webserver
  name: local-webserver
  namespace: inverter-edge
spec:
  host: inverter-{{ .Device.fingerprint | short }}.local
  port:
    targetPort: 80
  to:
    kind: Service
    name: local-webserver
    weight: 100
  wildcardPolicy: None