apiVersion: v1alpha1
kind: Fleet
metadata:
  name: quadlet-wordpress-fleet
spec:
  selector:
    matchLabels:
      fleet: quadlet-wordpress-fleet
  template:
    spec:
      os:
        image: quay.io/oglok/flightctl-device:basic
      config:
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
        - name: quadlets
          configType: GitConfigProviderSpec
          gitRef:  
            repository: quadlet-wordpress-demo
            targetRevision: main
            path: /demos/quadlet-wordpress-demo/configuration/etc/containers/systemd/
            mountPath: /etc/containers/systemd
      systemd:
        matchPatterns:
          - "wordpress-app.service"
          - "wordpress-db.service"
