version: "3.8"
services:
  kiosk:
    image: docker.io/library/python:3.11-slim
    working_dir: /app
    command: ["python", "-m", "http.server", "8080"]
    volumes:
      - /var/kiosk/catalog:/app:ro,z
    ports:
      - "8080:8080"
